-- Oscar Palace: rerunnable seed for current projects/project_subpages schema.
-- VERIFY: source classifies the listing as Upcoming; no brochure PDF or map embed was exposed.
BEGIN;
DO $$
DECLARE v_project_id uuid;
BEGIN
  SELECT id INTO v_project_id FROM public.projects WHERE title ILIKE 'Oscar Palace%' AND location ILIKE '%Indore%' ORDER BY created_at ASC LIMIT 1;
  IF v_project_id IS NULL THEN
    INSERT INTO public.projects (id,title,tag,image_url,location,description,type,status,featured,sort_order,feature_order)
    VALUES (gen_random_uuid(),'Oscar Palace','A Royal Estate for Your Palatial Abode','/projects/oscar-palace/hero.jpg','Indore','A 60+ acre premium plotted township at Hingoniya, off Indore Nagpur Highway.','Township','Upcoming',true,17,17) RETURNING id INTO v_project_id;
  ELSE
    UPDATE public.projects SET title='Oscar Palace',tag='A Royal Estate for Your Palatial Abode',image_url='/projects/oscar-palace/hero.jpg',location='Indore',description='A 60+ acre premium plotted township at Hingoniya, off Indore Nagpur Highway.',type='Township',status='Upcoming',featured=true,sort_order=17,feature_order=17 WHERE id=v_project_id;
  END IF;
  DELETE FROM public.project_subpages WHERE project_id=v_project_id;
  INSERT INTO public.project_subpages (project_id,hero_title,hero_tagline,hero_logo,hero_bg,overview_paragraphs,overview_highlights,amenities,specifications,location_image,location_map_embed,location_destinations,walkthrough_video_id,gallery_images,brochure_url,meta_title,meta_description,is_published) VALUES (
    v_project_id,'Oscar Palace','Royally Yours','/projects/oscar-palace/logo.png','/projects/oscar-palace/hero.jpg',
    $json$["A royal estate for your palatial abode. An estate that radiates luxury and becomes a statement of your stature for others. Oscar Palace is conceived to transform township living into a royal experience. Unique location, palace-like entrance, multiple themed gardens, baradaris and walkways, wide internal roads with palace inspired installations, and fort like boundary wall, it is an oasis of luxury.","In the tradition of other Oscar townships, the master planning of Oscar Palace is driven by the thought of making everyday living a royal experience.","Oscar Palace is a tribute to your taste and vision. It is royally yours!"]$json$::jsonb,
    $json$[{"label":"Area","desc":"60+ acres","icon":"infrastructure"},{"label":"Location","desc":"Hingoniya, Off Indore Nagpur Highway","icon":"location"},{"label":"Plot Size","desc":"3,500 to 20,000 sq ft","icon":"size"}]$json$::jsonb,
    $json$[{"name":"Tennis & Basketball Court","icon":"tennis"},{"name":"Kids Play Area","icon":"playground"},{"name":"Temple","icon":"temple"},{"name":"Water Fountains","icon":"garden"},{"name":"Yoga & Meditation Spaces","icon":"yoga"},{"name":"Baradaris, Chhatris & Gazebos","icon":"club"},{"name":"Senior Citizen Park","icon":"garden"},{"name":"Open Gym","icon":"gym"},{"name":"Watch Tower","icon":"security"},{"name":"Airwalk Way","icon":"jogging"}]$json$::jsonb,
    $json$[{"title":"Key Location","desc":"The 60+ acres expanse of Oscar Palace gives you the freedom of choice. With plot sizes ranging from 325 to 1,858 sq mtr (3,500 to 20,000 sq ft), you may build a palatial house or a modern villa, whatever suits your lifestyle."},{"title":"Project Details","desc":"Hingoniya, Off Indore Nagpur Highway, Besides Ruchi Lifescapes, Jhalariya, Indore - 452016, Madhya Pradesh. Registration ID: P-IND-24-4828. Phone: +91 89292 25275. Email: emarketing@rrhlrealty.com"},{"title":"__hero_media__","desc":"{\"type\":\"youtube_video\",\"url\":\"https://www.youtube.com/embed/ukNbmZfb2tY?autoplay=1&mute=1&loop=1&playlist=ukNbmZfb2tY&controls=0&showinfo=0&rel=0&modestbranding=1&disablekb=1&iv_load_policy=3&cc_load_policy=0\"}"},{"title":"__floor_plans__","desc":"[{\"title\":\"Layout Plan\",\"desc\":\"/projects/oscar-palace/plan.webp\"}]"},{"title":"__video_section__","desc":"{\"enabled\":true,\"title\":\"Layout Walkthrough\",\"videoUrl\":\"https://www.youtube.com/watch?v=0E0QQrL3ZyE\",\"thumbnailUrl\":\"/projects/oscar-palace/walkthrough-thumb.webp\"}"}]$json$::jsonb,
    '/projects/oscar-palace/loc-1.jpg','',$json$[{"name":"Hingoniya","dist":"Off Indore Nagpur Highway"},{"name":"Ruchi Lifescapes, Jhalariya","dist":"Besides project"},{"name":"Registration ID","dist":"P-IND-24-4828"}]$json$::jsonb,
    'https://www.youtube.com/watch?v=0E0QQrL3ZyE',$json$[{"src":"/projects/oscar-palace/gallery-g-1.webp","alt":"Oscar Palace gallery image 1"},{"src":"/projects/oscar-palace/gallery-g-2.webp","alt":"Oscar Palace gallery image 2"},{"src":"/projects/oscar-palace/gallery-g-3.webp","alt":"Oscar Palace gallery image 3"},{"src":"/projects/oscar-palace/gallery-g-4.webp","alt":"Oscar Palace gallery image 4"},{"src":"/projects/oscar-palace/gallery-g-5.webp","alt":"Oscar Palace gallery image 5"}]$json$::jsonb,
    '','Oscar Palace Indore - Ruchi Realty','Oscar Palace is a 60+ acre premium plotted township at Hingoniya, off Indore Nagpur Highway, offering 3,500 to 20,000 sq ft plots, palace-inspired landscapes, themed gardens, wide internal roads, and royal estate living.',true);
END $$;
COMMIT;