-- Generated from the cleaned legacy records in src/data/siteData.js.
begin;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Luxury living at One Victoria, New Town Kolkata','one-victoria-kolkata-luxury-living','A premium look at One Victoria as a high-rise residential address in New Town, Kolkata, with 3 BHK and 4 BHK homes shaped around connectivity, lifestyle, and long-term value.','One Victoria is positioned as a premium high-rise residential project in New Town, Kolkata, with modern 3 BHK and 4 BHK apartments for buyers seeking skyline-oriented living.

The article frames New Town as a strong residential address because of its access to IT hubs, retail, education, healthcare, and airport connectivity.

It also highlights lifestyle amenities such as a sky deck, infinity pool, clubhouse, gym, yoga and jogging spaces, and landscaped gardens, presenting the project as both a lifestyle upgrade and a long-term investment opportunity.','deepak ruchi_realty','/assets/blogs/one-victoria-kolkata.webp','One Victoria Kolkata','{}','News',true,'published','2024-12-01T00:00:00.000Z','Luxury living at One Victoria, New Town Kolkata | Ruchi Realty','A premium look at One Victoria as a high-rise residential address in New Town, Kolkata, with 3 BHK and 4 BHK homes shaped around connectivity, lifestyle, and long-te','https://ruchirealty.com/blogs/one-victoria-kolkata-luxury-living','Luxury living at One Victoria, New Town Kolkata','A premium look at One Victoria as a high-rise residential address in New Town, Kolkata, with 3 BHK and 4 BHK homes shaped around connectivity, lifestyle, and long-te','/assets/blogs/one-victoria-kolkata.webp',1,'https://ruchirealty.com/one-victoria-kolkata-the-future-of-real-estate-unveiling-growth-in-indore-and-kolkatas-new-town/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Real estate growth in Indore and Kolkata New Town','real-estate-growth-indore-kolkata-new-town','A market explainer on two strategic growth corridors: Indore and Kolkata''s New Town, and why both matter for homebuyers and investors.','This article frames India''s real-estate growth through Indore and Kolkata New Town, two markets shaped by infrastructure, connectivity, and rising residential demand.

Indore is presented as a Tier-2 growth hub with central location advantages, industrial momentum, infrastructure upgrades, and Smart City development.

New Town, Kolkata is positioned as a planned urban corridor supported by IT activity, connectivity, and demand for well-located residential communities.','Ruchi Realty','/assets/blogs/real-estate-growth-indore-kolkata.webp','Real Estate Growth','{}','Investment',false,'published','2024-12-01T00:00:00.000Z','Real estate growth in Indore and Kolkata New Town | Ruchi Realty','A market explainer on two strategic growth corridors: Indore and Kolkata''s New Town, and why both matter for homebuyers and investors.','https://ruchirealty.com/blogs/real-estate-growth-indore-kolkata-new-town','Real estate growth in Indore and Kolkata New Town','A market explainer on two strategic growth corridors: Indore and Kolkata''s New Town, and why both matter for homebuyers and investors.','/assets/blogs/real-estate-growth-indore-kolkata.webp',1,'https://ruchirealty.com/the-future-of-real-estate-unveiling-growth-in-indore-and-kolkatas-new-town/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Top 5 residential projects in Kolkata by Ruchi Realty','top-5-residential-projects-kolkata','A project-discovery guide covering Active Acres, One Victoria, One Prime, One Rajarhat, and Angelica across Kolkata.','This listicle introduces five Ruchi Realty residential projects in Kolkata: Active Acres, One Victoria, One Prime, One Rajarhat, and Angelica.

The focus is on location, lifestyle value, everyday convenience, and amenities, helping buyers compare multiple Ruchi Realty addresses in one place.

It is useful for project discovery, internal linking, and search-led content around residential projects in Kolkata.','Ruchi Realty','/assets/blogs/top-5-residential-projects-kolkata.webp','Top 5 Residential Projects in Kolkata by Ruchi Realty','{}','News',false,'published','2024-12-01T00:00:00.000Z','Top 5 residential projects in Kolkata by Ruchi Realty | Ruchi Realty','A project-discovery guide covering Active Acres, One Victoria, One Prime, One Rajarhat, and Angelica across Kolkata.','https://ruchirealty.com/blogs/top-5-residential-projects-kolkata','Top 5 residential projects in Kolkata by Ruchi Realty','A project-discovery guide covering Active Acres, One Victoria, One Prime, One Rajarhat, and Angelica across Kolkata.','/assets/blogs/top-5-residential-projects-kolkata.webp',1,'https://ruchirealty.com/top-5-residential-projects-in-kolkata-by-ruchi-realty/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('How to evaluate the value of a plot','how-to-evaluate-plot-value','A practical buyer guide explaining why plot value depends on more than size and asking price.','This educational guide explains that plot value depends on location, accessibility, zoning, dimensions, soil, topography, utilities, and surrounding development.

It encourages buyers to check infrastructure, nearby amenities, legal documents, and market trends before committing to land or plotted developments.

The article works well as trust-building content for buyers evaluating plotted townships or long-term land investments.','Ruchi Realty','/assets/blogs/evaluate-plot-value.webp','Plot value evaluation guide','{}','Buying Guide',false,'published','2024-06-01T00:00:00.000Z','How to evaluate the value of a plot | Ruchi Realty','A practical buyer guide explaining why plot value depends on more than size and asking price.','https://ruchirealty.com/blogs/how-to-evaluate-plot-value','How to evaluate the value of a plot','A practical buyer guide explaining why plot value depends on more than size and asking price.','/assets/blogs/evaluate-plot-value.webp',1,'https://ruchirealty.com/how-to-evaluate-the-value-of-a-plot/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Investment advantages in Indore real estate','investment-advantages-indore-real-estate','A focused look at why Indore''s infrastructure, connectivity, industrial growth, and planned development are attracting property investors.','The article positions Indore as a fast-growing real-estate market with strong infrastructure, economic appeal, and central location advantages.

It highlights connectivity, industrial growth, planned development, residential demand, rental potential, and appreciation possibilities as investment drivers.

Ruchi Realty''s presence in Indore is connected with trusted development, prime locations, amenities, and long-term value.','Ruchi Realty','/assets/blogs/indore-real-estate-investment.webp','Investment Advantages in Real Estate Sector','{}','Investment',false,'published','2024-05-01T00:00:00.000Z','Investment advantages in Indore real estate | Ruchi Realty','A focused look at why Indore''s infrastructure, connectivity, industrial growth, and planned development are attracting property investors.','https://ruchirealty.com/blogs/investment-advantages-indore-real-estate','Investment advantages in Indore real estate','A focused look at why Indore''s infrastructure, connectivity, industrial growth, and planned development are attracting property investors.','/assets/blogs/indore-real-estate-investment.webp',1,'https://ruchirealty.com/investment-advantages-in-real-estate-sector-2/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Ruchi Lifescapes Indore and premium plotted living','ruchi-lifescapes-indore-premium-plots','A project-led article presenting Ruchi Lifescapes Indore as a premium plotted township in Jhalaria.','Ruchi Lifescapes Indore is introduced as a premium plotted development in Jhalaria, Indore, with plots, villas, and row-house style lifestyle possibilities.

The article mentions amenities such as clubhouse, pool, gardens, gym, children''s play areas, basketball, and tennis.

It positions the development around convenience, safety, greenery, community lifestyle, and future value.','Ruchi Realty','/assets/blogs/ruchi-lifescapes-indore-premium-plots.webp','Ruchi Lifescapes Indore premium plots','{}','Buying Guide',false,'published','2024-05-01T00:00:00.000Z','Ruchi Lifescapes Indore and premium plotted living | Ruchi Realty','A project-led article presenting Ruchi Lifescapes Indore as a premium plotted township in Jhalaria.','https://ruchirealty.com/blogs/ruchi-lifescapes-indore-premium-plots','Ruchi Lifescapes Indore and premium plotted living','A project-led article presenting Ruchi Lifescapes Indore as a premium plotted township in Jhalaria.','/assets/blogs/ruchi-lifescapes-indore-premium-plots.webp',1,'https://ruchirealty.com/premium-plots-in-indore-2/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('First-time property buyer''s guide','first-time-property-buyer-guide','A beginner-friendly guide covering budgeting, additional costs, location, property type, amenities, and long-term livability.','This buyer guide walks first-time property buyers through budgeting, additional costs, location decisions, property type, and lifestyle fit.

It explains the importance of amenities, long-term livability, connectivity, convenience, and appreciation potential.

Ruchi Lifescapes is referenced as an example of a feature-rich residential option for buyers comparing long-term choices.','Ruchi Realty','/assets/blogs/first-time-property-buyer-guide.webp','Buying Property','{}','Buying Guide',false,'published','2024-04-01T00:00:00.000Z','First-time property buyer''s guide | Ruchi Realty','A beginner-friendly guide covering budgeting, additional costs, location, property type, amenities, and long-term livability.','https://ruchirealty.com/blogs/first-time-property-buyer-guide','First-time property buyer''s guide','A beginner-friendly guide covering budgeting, additional costs, location, property type, amenities, and long-term livability.','/assets/blogs/first-time-property-buyer-guide.webp',1,'https://ruchirealty.com/buying-property-for-the-first-time-heres-your-buyers-guide-to-the-right-purchase/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Oscar Pride as an Indore investment opportunity','oscar-pride-indore-investment','An investment-focused article on Oscar Pride, its Kanadia Main Road context, Bypass connectivity, and long-term growth potential.','Oscar Pride is presented as a residential investment opportunity in Indore, with attention to Kanadia Main Road and Bypass connectivity.

The article mentions nearby lifestyle and education anchors, including schools and retail destinations, while emphasizing design, amenities, and appreciation potential.

It frames Oscar Pride as a smart choice for buyers seeking growing returns in Indore.','Ruchi Realty','/assets/blogs/oscar-pride-investment.webp','Oscar Pride Investment','{}','Investment',false,'published','2024-04-01T00:00:00.000Z','Oscar Pride as an Indore investment opportunity | Ruchi Realty','An investment-focused article on Oscar Pride, its Kanadia Main Road context, Bypass connectivity, and long-term growth potential.','https://ruchirealty.com/blogs/oscar-pride-indore-investment','Oscar Pride as an Indore investment opportunity','An investment-focused article on Oscar Pride, its Kanadia Main Road context, Bypass connectivity, and long-term growth potential.','/assets/blogs/oscar-pride-investment.webp',1,'https://ruchirealty.com/unleash-the-potential-of-oscar-pridea-wise-investment-for-growing-returns/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Ruchi Lifescapes and serene township living','ruchi-lifescapes-serene-lifestyle','A lifestyle-led piece around peaceful living, green open spaces, and community-focused township design.','This article highlights peaceful living, green open spaces, and community-focused township planning at Ruchi Lifescapes.

It mentions amenities such as clubhouse, wide roads, gardens, pool, gym, children''s areas, basketball, and security.

The piece connects lifestyle comfort with connectivity to highways, malls, and schools.','Ruchi Realty','/assets/blogs/ruchi-lifescapes-serene-lifestyle.webp','Ruchi Lifescapes Bhopal','{}','News',false,'published','2024-03-01T00:00:00.000Z','Ruchi Lifescapes and serene township living | Ruchi Realty','A lifestyle-led piece around peaceful living, green open spaces, and community-focused township design.','https://ruchirealty.com/blogs/ruchi-lifescapes-serene-lifestyle','Ruchi Lifescapes and serene township living','A lifestyle-led piece around peaceful living, green open spaces, and community-focused township design.','/assets/blogs/ruchi-lifescapes-serene-lifestyle.webp',1,'https://ruchirealty.com/ruchi-lifescapes-an-epitome-of-serene-lifestyle/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Benefits of gated community living at Oscar Pride','oscar-pride-gated-community-living','A clear guide to gated-community benefits, using Oscar Pride''s secure, amenity-led environment as the example.','The article explains gated community benefits such as security, privacy, shared amenities, and a stronger community environment.

Oscar Pride is described around its 8-acre setting near Kanadia Main Road, Indore, with guarded entry, CCTV, controlled access, and safe play areas.

Lifestyle amenities mentioned include gym, lily pond, temple, kids'' play area, selfie wall, BBQ space, jogging track, and senior garden.','Ruchi Realty','/assets/blogs/oscar-pride-gated-community.webp','Oscar Pride Park','{}','News',false,'published','2024-03-01T00:00:00.000Z','Benefits of gated community living at Oscar Pride | Ruchi Realty','A clear guide to gated-community benefits, using Oscar Pride''s secure, amenity-led environment as the example.','https://ruchirealty.com/blogs/oscar-pride-gated-community-living','Benefits of gated community living at Oscar Pride','A clear guide to gated-community benefits, using Oscar Pride''s secure, amenity-led environment as the example.','/assets/blogs/oscar-pride-gated-community.webp',1,'https://ruchirealty.com/owning-a-home-at-oscar-pride-the-benefits-of-gated-community-living/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Why invest in real estate in 2024','why-invest-in-real-estate-2024','A top-funnel investment article covering infrastructure, market recovery, Tier-2 growth, and plotted investment demand.','This investment article discusses real-estate opportunity in India with focus on Tier-2 and Tier-3 growth markets.

It mentions infrastructure development, government initiatives, market recovery, and plotted investment demand.

Indore is used as an example market, with references to Ruchi Lifescapes, Oscar Pride, and Saatvik Vihar. The original URL ends in 2023 while the visible title references 2024, so any migration should preserve or redirect carefully.','Ruchi Realty','/assets/blogs/invest-in-real-estate-2024.webp','Growth Ruchi Realty','{}','Investment',false,'published','2024-02-01T00:00:00.000Z','Why invest in real estate in 2024 | Ruchi Realty','A top-funnel investment article covering infrastructure, market recovery, Tier-2 growth, and plotted investment demand.','https://ruchirealty.com/blogs/why-invest-in-real-estate-2024','Why invest in real estate in 2024','A top-funnel investment article covering infrastructure, market recovery, Tier-2 growth, and plotted investment demand.','/assets/blogs/invest-in-real-estate-2024.webp',1,'https://ruchirealty.com/why-should-you-invest-in-real-estate-in-2023/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('Luxury living at Ruchi Lifescapes','ruchi-lifescapes-luxury-living','An aspiration-led plot-buying article about building a future home in a planned, green, amenity-rich community.','Ruchi Lifescapes is positioned as a luxury plotted community for buyers who want to build a dream home around future lifestyle needs.

The article highlights planned township living, green landscapes, connectivity, amenities, and peaceful surroundings.

It blends lifestyle aspiration with investment value for plot buyers.','Ruchi Realty','/assets/blogs/ruchi-lifescapes-luxury-living.webp','Ruchi Lifescapes luxury plotted community','{}','News',false,'published','2024-02-01T00:00:00.000Z','Luxury living at Ruchi Lifescapes | Ruchi Realty','An aspiration-led plot-buying article about building a future home in a planned, green, amenity-rich community.','https://ruchirealty.com/blogs/ruchi-lifescapes-luxury-living','Luxury living at Ruchi Lifescapes','An aspiration-led plot-buying article about building a future home in a planned, green, amenity-rich community.','/assets/blogs/ruchi-lifescapes-luxury-living.webp',1,'https://ruchirealty.com/experience-luxury-living-at-ruchi-lifescapes-discover-your-dream-plot/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
insert into public.blogs(title,slug,excerpt,content,author,image,image_alt,tags,category,featured,status,published_at,seo_title,seo_description,canonical_url,og_title,og_description,og_image_url,reading_time_minutes,old_url) values ('How to know if you are getting a good property price','good-property-price-guide','A buyer education piece on comparing similar properties, understanding local demand, and evaluating whether a price is fair.','This guide explains how buyers can assess whether a property is priced fairly before negotiating or closing a deal.

It recommends comparing similar properties, reviewing listings, and understanding local supply and demand.

The article also suggests considering future development prospects, lender valuation, inspection findings, and repair or improvement costs.','Ruchi Realty','/assets/blogs/good-property-price.webp','Investment Opportunity','{}','Buying Guide',false,'published','2023-12-01T00:00:00.000Z','How to know if you are getting a good property price | Ruchi Realty','A buyer education piece on comparing similar properties, understanding local demand, and evaluating whether a price is fair.','https://ruchirealty.com/blogs/good-property-price-guide','How to know if you are getting a good property price','A buyer education piece on comparing similar properties, understanding local demand, and evaluating whether a price is fair.','/assets/blogs/good-property-price.webp',1,'https://ruchirealty.com/how-to-know-youre-getting-a-good-price/') on conflict(slug) do update set excerpt=excluded.excerpt,content=excluded.content,image=excluded.image,image_alt=excluded.image_alt,seo_title=excluded.seo_title,seo_description=excluded.seo_description,canonical_url=excluded.canonical_url,og_image_url=excluded.og_image_url,old_url=excluded.old_url;
commit;
